function [game] = game_create(height, width)
game = [];
game.board = board_create(height, width);
game.checkpoints = [];
game.robots = struct('identity',          {}, ...
                     'position',          {}, ...
                     'direction',         {}, ...
                     'respawn_position',  {}, ...
                     'respawn_direction', {}, ...
                     'next_checkpoint',   {}, ...
                     'damage',            {}, ...
                     'state',             {}, ...
                     'is_virtual',        {}, ...
                     'registers',         {});
