function [ tiles ] = PlaceObjects( tiles,i,j,x )
%the original tiles array did not have numbers for the checkpoints.
%we can assign 13 - 16 for checkpoints 1-4
if(x==1)
    tiles(i,j,13)=1;
end
if(x==2)
    tiles(i,j,14)=1;
end
if(x==3)
    tiles(i,j,15)=1;
end
if(x==4)
    tiles(i,j,16)=1;
end
%-------%

if(x==5)
    tiles(i,j,1)=1;
end
if(x==6)
    tiles(i,j,5)=1;
end
if(x==7)
    tiles(i,j,3)=1;
end
if(x==8)
    tiles(i,j,4)=1;
end
if(x==9)
    tiles(i,j,6)=1;
end
if(x==10)
    tiles(i,j,3)=1;
    tiles(i,j,4)=1;
end
if(x==11)
    tiles(i,j,3)=1;
    tiles(i,j,6)=1;
end
if(x==12)
    tiles(i,j,4)=1;
    tiles(i,j,5)=1;
end
if(x==13)
    tiles(i,j,5)=1;
    tiles(i,j,6)=1;
end
if(x==14)
    tiles(i,j,9)=1;
end
if(x==15)
    tiles(i,j,7)=1;
end
if(x==16)
    tiles(i,j,10)=1;
end
if(x==17)
    tiles(i,j,8)=1;
end
if(x==18)
    tiles(i,j,11)=1;
    tiles(i,j,7)=1;
end
if(x==19)
    tiles(i,j,11)=1;
    tiles(i,j,10)=1;
end
if(x==20)
    tiles(i,j,9)=1;
    tiles(i,j,11)=1;
end
if(x==21)
    tiles(i,j,11)=1;
    tiles(i,j,8)=1;
end
if(x==22)
    tiles(i,j,10)=1;
    tiles(i,j,12)=1;
end
if(x==23)
    tiles(i,j,7)=1;
    tiles(i,j,12)=1;
end
if(x==24)
    tiles(i,j,8)=1;
    tiles(i,j,12)=1;
end
if(x==25)
    tiles(i,j,9)=1;
    tiles(i,j,12)=1;
end
if(x==26)
    tiles(i,j,2)=1;
end

end

